CREATE TABLE [dbo].[Job](
	[Id] [BIGINT] IDENTITY(1,1) NOT NULL,
	[TargetId] [BIGINT] NOT NULL,
	[JobTypeId] [BIGINT] NOT NULL,
	[JobStateId] [BIGINT] NOT NULL,
	[UserId] [BIGINT] NULL,
	[NotifyWhenComplete] [BIT] NOT NULL,
	[ErpIntegrationErrorCode] [INT] NULL,
	[CreatedBy] [NVARCHAR](MAX) NULL,
	[UTCCreated] [DATETIME] NOT NULL,
	[UTCStarted] [DATETIME] NULL,
	[UTCFinished] [DATETIME] NULL,
	[IsMonitored] [BIT] NOT NULL DEFAULT ((0)),
 CONSTRAINT [PK_Job] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

