//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationMaker.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntegrationMakerEntities : DbContext
    {
        public IntegrationMakerEntities()
            : base("name=IntegrationMakerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Integration> Integrations { get; set; }
        public virtual DbSet<IntegrationCredential> IntegrationCredentials { get; set; }
        public virtual DbSet<IntegrationErrorCode> IntegrationErrorCodes { get; set; }
        public virtual DbSet<IntegrationType> IntegrationTypes { get; set; }
        public virtual DbSet<IntegrationLog> IntegrationLogs { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobLog> JobLogs { get; set; }
        public virtual DbSet<JobState> JobStates { get; set; }
        public virtual DbSet<JobTransferDetail> JobTransferDetails { get; set; }
        public virtual DbSet<JobType> JobTypes { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyUser> CompanyUsers { get; set; }
    }
}
