//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationMaker.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationCredential
    {
        public long Id { get; set; }
        public string AccountIdentifier { get; set; }
        public string Username { get; set; }
        public long IntegrationId { get; set; }
        public string Password { get; set; }
        public string Token { get; set; }
        public System.DateTime CratedUTC { get; set; }
        public Nullable<System.DateTime> LastModifiedUTC { get; set; }
    
        public virtual Integration Integration { get; set; }
    }
}
