//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationMaker.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.JobLogs = new HashSet<JobLog>();
            this.JobTransferDetails = new HashSet<JobTransferDetail>();
        }
    
        public long Id { get; set; }
        public long TargetId { get; set; }
        public long JobTypeId { get; set; }
        public long JobStateId { get; set; }
        public Nullable<long> UserId { get; set; }
        public bool NotifyWhenComplete { get; set; }
        public Nullable<int> ErpIntegrationErrorCode { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UTCCreated { get; set; }
        public Nullable<System.DateTime> UTCStarted { get; set; }
        public Nullable<System.DateTime> UTCFinished { get; set; }
        public bool IsMonitored { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobLog> JobLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobTransferDetail> JobTransferDetails { get; set; }
    }
}
